credentials:
  system:
    domainCredentials:
      - domain:
          name: "git"
      - credentials:
          - string:
              scope: GLOBAL
              id: "SomeID"
              secret: "some secret text"
              description: "Some description"
